### PR TITLE
Fix compilation of plurals when msgstr only contains one element

### PR DESCRIPTION
**Pull request by maufl**
This should fix the problem described in #18

### CODE REVIEW

**Comment by andris9** [comment]
Published as v1.2.0. Also added a note to README that this project is unmaintained, I don't plan to continue maintaining it. If anyone wants to take over, let me know (andris.reinman@gmail.com)

**Comment by maufl** [comment]
Thank you very much!

**Comment by alexanderwallin** [comment]
@andris9 Do you have conceptual arguments to why you don't want to maintain it, or is it more in terms of lack of time/interest?

**Comment by andris9** [comment]
Both time and interest as I don't need this module myself anymore. I don't think there's something wrong with it and gettext format itself is decades old so there should not happen any changes but occasionally there's still some things to do (for example node v6 changed buffer api, so in the future this module needs some updating as well in this regard).

**Pull request merged**
